### ISSUE TITLE
Older version 

### ISSUE THREAD

**Issue by Wreaking** [SakiyaDev/anti-phish-advanced#1]
I actually using djsV12 not 13 do you know what version does your package support djsV12?

**Comment by tsukuyomiotoko** [comment]
Hey, v12 is not currently supported but we might look into supporting it if there are other people (who use v12) who would like to use this package. Thanks

*P.S. I would highly recommending staying up to date (upgrading to v13) because they're going to be dropping support for v12 soon.*

**Comment by tsukuyomiotoko** [comment]
Hey we support it now!

**Comment by Wreaking** [comment]
Thanks mate!!
