### ISSUE TITLE
can you add edit msg check

### ISSUE THREAD

**Issue by APOORVBG** [SakiyaDev/anti-phish-advanced#4]
can you add a way so that it will even check edited msg 
if this package was made in await i could have added this in message update event
bot its in his own event so :v

i just want you to make a way to prevent phishing by editing msg

**Comment by EmiliaShiori** [comment]
Sorry for the late responce, I'll send this to the person who manages the package, And I'll let you know of any updates

**Comment by APOORVBG** [comment]
thanks

**Comment by tsukuyomiotoko** [comment]
Hey there! Working on it right now, a new update should be out tomorrow if I finish testing by then! Please hang tight, thank you!

**Comment by tsukuyomiotoko** [comment]
Hey there! So it should work now, let me know if it doesn't! (Don't forget to update by doing `npm i anti-phish-advanced`)
