### ISSUE TITLE
README: Stating which API it uses

### ISSUE THREAD

**Issue by ByteAlex** [SakiyaDev/anti-phish-advanced#5]
Hi, I'm the maintainer of https://bitflow.dev/anti-fish and I'd love to see that link somewhere in your README. This will help people to find the API Server (which you're also not on just yet, check out the website!) and report missing domains and/or false-positives there.
Also I like to see a little credit to me ;)
Thank you!

**Comment by EmiliaShiori** [comment]
Sorry for the late response
I have credited you in the readme, super sorry my friend who credited the package didnt credit you at all for this. 
Feel free to add me on discord if you have any other issues / concerns Emilia#1605

**Comment by ByteAlex** [comment]
Thank you!

**Comment by tsukuyomiotoko** [comment]
Hey, looks like this got dealt with but super sorry for that!
